import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import yaml from 'js-yaml';
import type { ResourceLimits } from '@oblihub/shared';
import { config } from '../config';
import { logger } from '../utils/logger';

const execFileP = promisify(execFile);

const OVERRIDE_FILENAME = 'docker-compose.override.oblihub.yml';
const HEADER = '# Auto-generated by Oblihub — do not edit; regenerated on Save\n';

function defaultCpuShares(priority: ResourceLimits['priority']): number {
  switch (priority) {
    case 'critical': return 2048;
    case 'normal': return 1024;
    case 'opportunistic': return 128;
  }
}

function formatMemoryBytes(bytes: number): string {
  // Compose accepts human-readable suffixes; prefer 'g' when the value is a clean GB, else 'm'.
  const mb = Math.floor(bytes / (1024 * 1024));
  if (mb % 1024 === 0 && mb >= 1024) return `${mb / 1024}g`;
  return `${mb}m`;
}

function buildServiceOverride(limits: ResourceLimits): Record<string, unknown> {
  const service: Record<string, unknown> = {};
  const resources: { limits?: Record<string, unknown> } = {};
  const limitsBlock: Record<string, unknown> = {};

  if (limits.cpuPercent != null) {
    const absoluteCpus = Math.round((limits.cpuPercent / 100) * os.cpus().length * 10) / 10;
    if (absoluteCpus > 0) limitsBlock.cpus = String(absoluteCpus);
  }

  if (limits.ramPercent != null) {
    const bytes = Math.floor((limits.ramPercent / 100) * os.totalmem());
    if (bytes > 0) limitsBlock.memory = formatMemoryBytes(bytes);
  }

  if (Object.keys(limitsBlock).length > 0) {
    resources.limits = limitsBlock;
    service.deploy = { resources };
  }

  const shares = limits.cpuShares != null ? limits.cpuShares : defaultCpuShares(limits.priority);
  service.cpu_shares = shares;

  // NVIDIA_VISIBLE_DEVICES semantics:
  //   null   → 'all'   (default; expose every GPU the runtime knows about)
  //   []     → 'none'  (deliberately hide all GPUs from the container)
  //   [...]  → csv     (expose only the listed indices, e.g. "0,1")
  const env: Record<string, string> = {};
  if (limits.visibleGpuIds == null) {
    env.NVIDIA_VISIBLE_DEVICES = 'all';
  } else if (limits.visibleGpuIds.length === 0) {
    env.NVIDIA_VISIBLE_DEVICES = 'none';
  } else {
    env.NVIDIA_VISIBLE_DEVICES = limits.visibleGpuIds.join(',');
  }
  service.environment = env;

  // Only set the NVIDIA runtime when at least one GPU is actually being exposed. Setting it when
  // NVIDIA_VISIBLE_DEVICES=none is harmless but noisy; skipping it keeps the override minimal.
  if (limits.visibleGpuIds == null || limits.visibleGpuIds.length > 0) {
    service.runtime = 'nvidia';
  }

  return service;
}

/**
 * Write the auto-managed compose override file into the stack's folder. The file layers on top of
 * the operator's own `docker-compose.yml` at `docker compose -f ... -f override up -d` time.
 *
 * Every service the operator wants capped receives the same override block — Compose merges these
 * into the base service. Services not listed keep whatever the base file says.
 */
export async function writeStackOverride(
  stackFolderName: string,
  serviceNames: string[],
  limits: ResourceLimits,
): Promise<void> {
  const dir = path.join(config.stacksDir, stackFolderName);
  await fs.mkdir(dir, { recursive: true });
  const filePath = path.join(dir, OVERRIDE_FILENAME);

  const serviceBlock = buildServiceOverride(limits);
  const services: Record<string, unknown> = {};
  for (const svc of serviceNames) {
    if (!svc) continue;
    services[svc] = serviceBlock;
  }

  const doc = { services };
  const body = yaml.dump(doc, { noRefs: true, lineWidth: 120 });
  await fs.writeFile(filePath, HEADER + body, 'utf8');
  logger.info({ stackFolderName, serviceCount: serviceNames.length }, 'Wrote resource override file');
}

export async function removeStackOverride(stackFolderName: string): Promise<void> {
  const filePath = path.join(config.stacksDir, stackFolderName, OVERRIDE_FILENAME);
  try {
    await fs.unlink(filePath);
    logger.info({ stackFolderName }, 'Removed resource override file');
  } catch (err: unknown) {
    const e = err as { code?: string };
    if (e?.code !== 'ENOENT') throw err;
  }
}

/**
 * Run `docker compose up -d` in the stack's dir. When the auto-managed override exists it's
 * layered on top of the base file; otherwise we call plain `docker compose up -d` which reverts
 * services to whatever the base file specifies (no caps).
 */
export async function applyStackOverride(
  stackFolderName: string,
): Promise<{ ok: boolean; stdout: string; stderr: string }> {
  const dir = path.join(config.stacksDir, stackFolderName);
  const overridePath = path.join(dir, OVERRIDE_FILENAME);
  let hasOverride = false;
  try {
    await fs.stat(overridePath);
    hasOverride = true;
  } catch { /* no override — plain up */ }

  const args = ['compose', '-f', 'docker-compose.yml'];
  if (hasOverride) args.push('-f', OVERRIDE_FILENAME);
  args.push('up', '-d');

  try {
    const { stdout, stderr } = await execFileP('docker', args, { cwd: dir, timeout: 60_000 });
    return { ok: true, stdout, stderr };
  } catch (err: unknown) {
    const e = err as { stdout?: string; stderr?: string; message?: string };
    logger.warn({ stackFolderName, err: e?.message }, 'docker compose up failed');
    return { ok: false, stdout: e?.stdout || '', stderr: e?.stderr || e?.message || '' };
  }
}
